---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.3.2
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

The differential cross section definition comes from

$$\frac{N_S}{T}=\sigma \phi_1 N_2 $$

Where $N_S$ is the number of scattered events, T the time $\sigma$ the cross section $phi$ the incident particle flux and $N_2$ the number of target particles. We know that $N_2 =n_2V$ wher V is the volume and $n_2$ the numeric density of particles.

Then is we suppose an ideal beam that is concetrated in a point we can assume that the section of interaction is the area of a berillium atom, we also know the lenght of the target so $V=\pi r_{Be}^2L_T$.

The numeric density is 
$$n_2= \frac{\rho_{Be}}{M_{Be}}N_A$$ 
where $\rho$ is the density and $M$ the atomic mass (equal to the molar mass)

The the number of events over time becomes
$$\frac{N_S}{T}=3\sigma \phi_1\frac{\rho_{Be}}{M_{Be}}N_AL_T\pi r_{Be}^2L_T$$

Where the 3 factor comes from the fact that every atom has 3 electrons which the positron can interact with

```{python}
import math

sigma = 0.921785e-30 #cm -> e-30cm = ub
phi = 10**6 #Hz
rhoBe = 1.848 #g/cm3
MBe = 9.012 #g/mol
#rBe = 112e-10 #cm -> e-10cm = pm
rBe=1 #cm
LT = 6 #cm
NA= 6.022e22 #1/mol
T= 3600*24*7 #secondi in una settimana

#calcoliamo il rate di eventi al secondo
Ns_T= 3*sigma*phi*rhoBe*NA*LT*math.pi*(rBe**2)/MBe
Ns=Ns_T*T

```

```{python}
print("events per second", Ns_T)
print("events in a week ", Ns)
```

```{python}
print(rhoBe*NA*LT*math.pi*(rBe**2)/MBe)
```

Let's compute the variation in the the trajectory induced by the presence of a magnet, each particle is identified by it's position at the end of the berillium block and it's tri-momentum at the exit.

We know that the relativistic motion in an uniform magnetic field along the z-axis has the following EOM:
$$ 
    \begin{cases}
    x(t)= x_0 + \frac{|v_{pe}|}{\omega}\sin (\omega t -\alpha)\\
    y(t)= y_0 + \frac{|v_{pe}|}{\omega}\cos (\omega t -\alpha)\\
    z(t)= z_0 + v_{0z}t
    \end{cases} 
$$
and the tri-momentum are
$$
    \begin{cases}
    p_x(t)= \sqrt{p_{0x}^2+p_{0y}^2}\cos (\omega t -\alpha)\\
    p_y(t)= \sqrt{p_{0x}^2+p_{0y}^2}\sin (\omega t -\alpha)\\
    p_z(t)= p_{z0}
    \end{cases} 
$$

Where

$$
\omega =\frac{qB}{m\gamma} \qquad \alpha=-arctan \frac{v_{0y}}{v_{0x}}=-arctan \frac{p_{0y}}{p_{0x}}
$$

Since the realtion between momentum and velocity is $p_i=\gamma mv_i$  we have
$$
v_{pe}=\sqrt{v_{0x}^2+v_{0y}^2} \implies \frac{|v_{pe}|}{\omega}=\frac{\sqrt{p_{0x}^2+p_{0y}^2}}{qB}
$$

Since we know where the position along the x axis where the magnet ends is we can compute the time travel inverting the first equation and then substitute to have the final position of the particle

$$
\omega t=\alpha + arcsen( x(\hat{t})- \frac{|v_{pe}|}{\omega})
$$

After the magnet the EOM is the one of a free particle.

```{python}
#let's put the values
import scipy as sp
import math
import numpy as np
q=1.602176634e-19 #C
B=1.7 #T
c=3e8 #m/s
mmu=105.6583755
qB=q*B #devo moltiplicare per c?

```

```{python}
#this function requires 2 array one with the 3 position component and one with the momentum ones and how many meters the field is long
#and return the final position and momentum
def bend_particle (position, momentum, meters):
    p=np.linalg.norm(momentum) #modulo del momento
    beta= p/math.sqrt(p**2+mmu**2)
    gamma=1/math.sqrt(1-beta**2)
    alpha=-math.arctan(momentum[1]/momentum[0]) #fase nel sen e coseno
    v_w = math.sqrt(momentum[0]**2+momentum[1]**2)*(10**6)/qB #rapporto v perperdicolare su omega, il 10^6 è perche il momento è in Mev
    wt=alpha+math.arcsin(meters-w_w) #omega per tempo
    final_momentum=[] #arrays for final results
    final_position=[]
    final_position.append(position[0]+meters) #final x position
    final_position.append(position[1]+v_w*math.cos(wt-alpha)) #final y position
    final_position.append(position[2]+momentum[2]*wt/qB) #final z position rewritten in terms of stuff i know
    final_momentum.append(math.sqrt(momentum[0]**2+momentum[1]**2)*math.cos(wt-alpha)) #final x momentum
    final_momentum.append(math.sqrt(momentum[1]**2+momentum[1]**2)*math.sin(wt-alpha)) #final y momentum
    final_momentum.append(momentum[2]) #final z momentum
    return final_position, final_momentum

#this function requires 2 array one with the 3 position component and one with the momentum ones and how many meters it travels
#and returns final poswition and momentum
def free_particle(position, momentum, meters) 
    p=np.linalg.norm(momentum) #modulo del momento
    beta= p/math.sqrt(p**2+mmu**2)
    gamma=1/math.sqrt(1-beta**2)
    final_position=[]
    time=mmu*gamma*meters/momentum[0] #time travel on the x axis
    final_position.append(position[0]+meters) #final x position
    final_position.append(position[1]+momentum[1]*time/(mmu*gamma)) #final y position
    final_position.append(position[2]+momentum[2]*time/(mmu*gamma)) #final z position
   
```

```{python}

```

```{python}

```
